### ISSUE TITLE
Add GR boundary

### ISSUE THREAD

**Issue by jacebrowning** [friendlycode/grparks#15]

**Comment by MuellerL** [comment]
Do we need a file for this?

**Comment by jacebrowning** [comment]
Nope. We have an example of the city's boundary here: https://github.com/friendlycode/grparks/commit/4901102925d02b57fbb51fda3d9ee5504ba65c3c

**Comment by joel6653** [comment]
This might help, too: http://global.mapit.mysociety.org/area/830596.html.

**Comment by joel6653** [comment]
should we use the polygon coordinates as published in jace's reference or in my reference, or is there a way to obtain this more dynamically (iow, can anyone figure out what's going on programmatically at my reference?)

**Comment by joel6653** [comment]
done
