### ISSUE TITLE
Develop landing page / page framework.

### ISSUE THREAD

**Issue by MuellerL** [friendlycode/grparks#23]
We need some framework built around the map. This can be simple, but should provide some context for the data. I'm imaging a simple page frame / border with the map inset.

**Comment by MuellerL** [comment]
Original wireframe is here:
https://docs.google.com/presentation/d/15eqjurgElT3uNq0TGKm2-aSk_heOy3BX86AkFc1JBDU/edit?usp=sharing

**Comment by MuellerL** [comment]
Change focus from "millage" to "Parks improvements"

**Comment by joel6653** [comment]
see http://friendlycode.github.io/grparks/map.html
