### ISSUE TITLE
Remove duplicate parks from OpenStreetMaps

### ISSUE THREAD

**Issue by joel6653** [friendlycode/grparks#27]
see sidebar at http://friendlycode.github.io/grparks/map.html to find numerous duplicate parks pulled from OpenStreetMaps ... one of them even has a duplicate on the other side of the same street!

**Comment by joel6653** [comment]
Is it possible that the finder.py that breaks the city down into "bounding blocks" (or whatever they're called) gets certain parks occurring in more than one block (often due to the parks' size), and so those are the parks that get into the parks.osm_gejson file twice?  Some of the parks duplicated are Alexander, Riverside, Riverwalk Trails, Huff, Ken-O-Sha and two or three others I can't recall right now.

**Comment by joel6653** [comment]
Could be easy to verify if we looked at the log files that the run produces (but I don't know where those log files are).

**Comment by Crevax** [comment]
It logs to stdout, so if you view the build log in Travis it should be there.

**Comment by joel6653** [comment]
thanks, I found the log file, but unfortunately it doesn't log the name of the parks found

however, I do see that it walks through quite a few "regions" and, since the offending parks are all larger ones, I'm becoming convinced that my theory is correct

@jacebrowning ?

**Comment by jacebrowning** [comment]
I am certain the log of parks from OSM (https://github.com/friendlycode/grparks/blob/gh-pages/parks.csv) used to contain only the 74-ish parks we cared about.

I suspect something has changed on OSM, in the OSM API, or in the library used communicate with the OSM library.

**Comment by MuellerL** [comment]
Interesting. Some of these are definitely NOT city parks (e.g. millenium
park, Ottawa Hills high school grounds). I believe we used to have a
separate list of parks that we asked the code to refer to when pulling from
OSM. Is that where the problem lies?


--
All the best,
Lee

**Comment by jacebrowning** [comment]
This is the logic that should be doing it: https://github.com/friendlycode/grparks/blob/6d97974017950ac33367a28d8553c25a04314a41/parks/main.py#L80-L82

**Comment by jacebrowning** [comment]
I've added more logging to the Travis CI output: https://github.com/friendlycode/grparks/pull/35

**Comment by joel6653** [comment]
Looking over the new log file, it indeed appears that the problematic parks are logged twice.  I found Riverside, Riverwalk Trails, Huff, and Alexander (the others were probably there, too).

**Comment by joel6653** [comment]
Never mind, I guess. I'll resolve this issue in the javascript code that loads the list of parks in the browser. Can't seem to do much with Alexander Park, as it really does come through from OpenStreetMaps twice, with different "unique" IDs.

**Comment by MuellerL** [comment]
Joel,

Alexander park is two separate polygons on opposite sides of the street,
but is one park. This is probably a challenge with Open Street Map
functionality, that each polygon is treated as a separate data point. We
might need to look into OSM protocol and see if there's a way to "link"
these as a multipart polygon. I'll take a look into this, but it might be a
bit of a delay. I'm traveling for work this month.


--
All the best,
Lee

**Comment by jacebrowning** [comment]
Worst case, we could make the park one big polygon that includes the street or create a thin connecting path between them.

**Comment by joel6653** [comment]
Perhaps a few of the volunteers who started to look at this at our last meeting can take another look now, with fixing Alexander as the much-reduced goal (rather than trying to fix the larger problem).

**Comment by joel6653** [comment]
@MuellerL , if the City of GR really considers Alexander's two parts as ONE park, then we should try to figure out a way to combine them in OpenStreetMaps (as previously discussed in this thread). Otherwise, we should keep them separate (?).  Can you verify?

**Comment by MuellerL** [comment]
It's considered one park.

**Comment by MuellerL** [comment]
I have edited Alexander Park on OTM to be one park, rather than two. 

@joel6653 is this the last remaining issue on this ticket? Can this be closed?

**Comment by joel6653** [comment]
@MuellerL: yup, closing
