### ISSUE TITLE
Replace the old page with the new alternate version

### ISSUE THREAD

**Issue by jacebrowning** [friendlycode/grparks#30]
This might be as simple as deleting `index.html` and renaming `map.html` to `index.html`.

**Comment by jacebrowning** [comment]
Looks good!

**Comment by MuellerL** [comment]
Looking awesome!


--
All the best,
Lee

**Comment by Allen616** [comment]
I concur. Thanks for digging into this and making the contributions.

**Comment by joel6653** [comment]
Aww, shucks. Just earning my pizza.
