### ISSUE TITLE
Make the map fill the screen

### ISSUE THREAD

**Issue by jacebrowning** [friendlycode/grparks#31]
At least in my browser (Chrome, OS X), there is a lot of unused space:

<img width="853" alt="screen shot 2016-01-29 at 10 04 40 am" src="https://cloud.githubusercontent.com/assets/939501/12679028/d223b83e-c66f-11e5-8a04-54166a7fb9b3.png">

**Comment by joel6653** [comment]
working on this, tried a bunch of things that didn't work, running out of time today
