### ISSUE TITLE
Add a note explaining what the millage number means

### ISSUE THREAD

**Issue by mikekokuba** [friendlycode/grparks#36]
I don't see any explanation of what the millage number means for each park.

**Comment by jacebrowning** [comment]
Something like a date range might also be helpful. And a "last updated" date.

**Comment by joel6653** [comment]
The more that could be supplied with the data coming from the city, the better.  Perhaps even a breakdown of what the millage was spent for on a park-by-park basis.  If it's in the data, it would be simple to include it in the popup or the grid or both.

**Comment by MuellerL** [comment]
Yes. I agree we need some explanation. The data by provided by the City is
on a "project" basis. Each project may include a multitude of improvements.
It would get quite tedious if we listed out every drinking fountain and new
sink, but we could definitely use their projects to split out the data by
"sports court resurfacing" or "general improvements" or "capital
improvements" (i.e. the rennovations in Cherry, Wilcox, Garfield, etc.).


--
All the best,
Lee

**Comment by joel6653** [comment]
The spot to show those remarks is ready, all we need is the data from the city.

**Comment by MuellerL** [comment]
Joel, where is this spot located? 

Now that we're further along, I can begin making some requests of the City for information.

**Comment by joel6653** [comment]
Take a fresh look at the app. Note the "tiles" view (upper-left corner is where you select if). When you get there, you'll be able to flip any tile with $$ in it.

**Comment by MuellerL** [comment]
Awesome. Thanks.

I'll talk with GR parks and make another data request.


--
All the best,
Lee

**Comment by joel6653** [comment]
@MuellerL has this in paper form, will work on getting the data in electronic form, after which @jacebrowning can ensure that it is included in the geojson file and then I can add it to the popups.

**Comment by joel6653** [comment]
added to millage.csv, verified that it carries over to geojson, added a few fake descriptions for testing/demonstration, now up to @MuellerL to make sure it gets into the source data
