### ISSUE TITLE
Other questions (for Lee?)

### ISSUE THREAD

**Issue by joel6653** [friendlycode/grparks#39]
( @MuellerL )

- should marker popups ALWAYS show the full information, or should that be reserved for when the user actually clicks on the $$$/i button in the info pane (as it is now)?
- do we want any marker popups to appear on HOVER? or only when clicked, as it is now?
- what about colors of both the city boundaries and the parks themselves?
- map style? on slack, I previously pointed out several alternatives ... we need to choose one
- is anyone able to supply a pair of geographical coordinates for the 2 or 3 parks that OSM can't locate the center of (the ones where the map marker appears outside the bounds of the park, e.g. Riverside)

**Comment by MuellerL** [comment]
Joel et al.

I'm unable to attend Tuesday. I wonder if its worth us sitting down
separately and mapping out some next steps. I also have some new park data,
although it's hard-copy. I'm going to ask the Parks for the electronic
version.


--
All the best,
Lee

**Comment by joel6653** [comment]
I’m open to suggestions. I would like to keep this project moving forward. What is your availability (and where)?

**Comment by MuellerL** [comment]
Joel,

How do you look for the 23rd, 24th, or 25th?


--
All the best,
Lee

**Comment by joel6653** [comment]
@MuellerL , early morning and late afternoon and evening for the 23rd (Wednesday), morning and evening for the 24th, morning and early afternoon for the 25th

p.s.: this kind of conversation is so much easier and less obtrusive on Slack (hint, hint)

**Comment by MuellerL** [comment]
Let's lock in the morning of the 24th. You call the time and place.


--
All the best,
Lee

**Comment by joel6653** [comment]
@MuellerL , early would be better. I can go as early as 8:00, but it depends on where. If you are able and willing to head south, there is a McDonald's on 44th St. near Clyde Park with good wi-fi and isolated spaces. If downtown works better for you, we could meet at the library (but more like 9:00, which is when they open). Anywhere in-between would also be OK, but I can't think of any convenient meeting spaces.

**Comment by MuellerL** [comment]
Joel,

I'll meet you at the 44th St McDonalds at 8a on 3/24. Talk then!


--
All the best,
Lee

**Comment by joel6653** [comment]
acknowledged

**Comment by Allen616** [comment]
The question of branding elements of the website came up at last night's meeting. The current site is using City of GR branding elements. Would it be OK/safer to use Friends of GR Parks branding elements (logo and color)? http://www.friendsofgrparks.org/parks/find-a-park/

**Comment by MuellerL** [comment]
I suppose it depends on who ultimately takes ownership of the product. To
date,  we've spoken primarily with the city.

**Comment by MuellerL** [comment]
Still planning on 8a tomorrow. Let me know if anything has changed.


--
All the best,
Lee

**Comment by joel6653** [comment]
nothing has changed (except the web site itself), I’m still looking forward to it

**Comment by joel6653** [comment]
@MuellerL and I resolved the issues in the original question as follows:

- marker popups will always show the full information
- marker popups will appear on HOVER, not just on click (except for touch devices)
- colors (for city boundary) had previously been determined (with @MaxwellDillivan )
- the default map style will be Emerald, with Grayscale serving as the single alternative (Streets and the github default have been eliminated)
- Lee will obtain the lat/lng coordinates for the two problematic parks, but we'll need @jacebrowning to help ensure that those items make it from the spreadsheet (when they begin appearing)  into the geojson data

I am working on implementing these changes, starting with the next commit.

**Comment by jacebrowning** [comment]
Want to split these out into new issues and close this one?

**Comment by joel6653** [comment]
@MuellerL, I'm going to back-pedal on the "marker popups will appear on HOVER" item. It was easy to put in place, but that's not the issue. As it turns out, when neighborhoods layer is turned on, with its own hover behavior, the two things fight one another for the user's attention. So I'm turning it back off. The other items will remain in process or done, as the case may be.

@jacebrowning, I'd be glad to move the remaining item (the lat/lng for strangely-shaped parks) into a separate issue here on github. Give me a few minutes, then I'll also close this one.
