### ISSUE TITLE
Allow for overriding the default "center of park" determination

### ISSUE THREAD

**Issue by joel6653** [friendlycode/grparks#40]
There are at least 2 parks which are so oddly-shaped that the leaflet method of determining the center of the park in order to locate the marker ends up placing it a block or two outside the park (leaflet draws a rectangle to contain the park's polygon, then computes the center of that). See Riverside Park for the best example.

What I propose is that we allow an extra column (or two) in the park data spreadsheet/csv file for the geographical coordinates of the *real* center. For most parks, this data could be left blank, in which case leaflet can use the default calculation. But for those exceptions (Riverside, etc.), filling this data in could override the default.

@MuellerL will obtain the lat/lng coordinates for the two problematic parks, but we'll need @jacebrowning to help ensure that those items make it from the spreadsheet (when they begin appearing) into the geojson data.

**Comment by joel6653** [comment]
closed related issue #37, in order to provide details of the proposed solution while eliminating the other issue's "chatter"

**Comment by MuellerL** [comment]
@joel6653 

Riverside Park: 43.011487, -85.668329
Wilcox Park: 42.959944, -85.630641
Hoskin Park: 42.959615, -85.644299

**Comment by joel6653** [comment]
next step: make sure that this data, if added to the city's spreadsheet, will filter through to the geojson file

**Comment by joel6653** [comment]
It will filter through. Next step, ensure that this data is entered into the source spreadsheet. It is in there now in the version that exists here on github, but the next time someone changes it at the source (at the city or other responsible party), they will have to make sure it's included. Reassigning.

**Comment by joel6653** [comment]
I entered the data from @MuellerL's list of coordinates (above) for Riverside, Louis Campau, and Wilcox; the other two (Hosken and Foster) didn't look that bad on the map to me, so I skipped them. Other parks that Lee didn't include (but that are also probably OK) are Campau, Fourth Street Woods, and Joe Taylor.

**Comment by joel6653** [comment]
@MuellerL, Wilcox now looks worse than it did before the adjustment.

**Comment by MuellerL** [comment]
I would try: 42.959683, -85.630724 or revert.


--
All the best,
Lee

**Comment by joel6653** [comment]
@MuellerL: that works, not perfectly, but at least it's actually IN the part

next step is to be sure that whoever becomes responsible for maintaining the data in the future remembers to include that in their csv file (or however it's transmitted) ... I'll leave this issue open until such time
