### ISSUE TITLE
Map missing parks on OSM.

### ISSUE THREAD

**Issue by MuellerL** [friendlycode/grparks#46]
Several missing parks need to be mapped.

**Comment by jacebrowning** [comment]
From the build log, I'm assuming these are the missing parks:

```
WARNING: __main__: missing park on OSM: Covell Dog Park
WARNING: __main__: missing park on OSM: Lexington Park
WARNING: __main__: missing park on OSM: Lincoln Place Park
WARNING: __main__: missing park on OSM: Ottawa Hills Park
WARNING: __main__: missing park on OSM: Rasberry Field
WARNING: __main__: missing park on OSM: Tremont Greenspace
```

**Comment by MuellerL** [comment]
All have been mapped.

Note that "Covell Dog Park" is a pre-existing feature in Open Street Map. That said, it's type is "Dog Park" rather than "Park." The code may need to be changed to match park names not only with "Park" but also type "Dog Park." 

@jacebrowning @joel6653
